# Generated by Django 4.0.6 on 2022-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_poll_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='option1',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='option2',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='option3',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='option4',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
